#!/usr/bin/env python3
"""
gen_imem_mif.py — Convert flat 32-bit hex firmware → 4 byte-lane IMEM MIF files.

Input:  fpga/dmem_lena.hex  (one 32-bit word per line, little-endian)
Output: fpga/imem_b0.mif  (bits [7:0]  of each instruction word)
        fpga/imem_b1.mif  (bits [15:8])
        fpga/imem_b2.mif  (bits [23:16])
        fpga/imem_b3.mif  (bits [31:24])

Each MIF: WIDTH=8, DEPTH=2048 (matches Quartus ROM IP config).
Unused entries filled with 0x00 (decodes as ADD x0,x0,x0 — safe NOP).

Usage: python fpga/gen_imem_mif.py
"""

import os, sys

DEPTH    = 2048
HEX_FILE = os.path.join(os.path.dirname(__file__), "dmem_lena.hex")
OUT_DIR  = os.path.dirname(__file__)

def mif_header(lane):
    return (
        f"-- IMEM byte lane {lane} — auto-generated by gen_imem_mif.py\n"
        f"WIDTH=8;\n"
        f"DEPTH={DEPTH};\n\n"
        f"ADDRESS_RADIX=HEX;\n"
        f"DATA_RADIX=HEX;\n\n"
        f"CONTENT BEGIN\n"
    )

# Read firmware words
words = []
with open(HEX_FILE) as f:
    for line in f:
        line = line.strip()
        if line:
            words.append(int(line, 16))

if len(words) > DEPTH:
    print(f"ERROR: firmware too large ({len(words)} words > DEPTH={DEPTH})")
    sys.exit(1)

# Pad to DEPTH with 0
words += [0] * (DEPTH - len(words))

# Generate 4 MIF files
for lane in range(4):
    path = os.path.join(OUT_DIR, f"imem_b{lane}.mif")
    shift = lane * 8
    with open(path, "w") as f:
        f.write(mif_header(lane))
        for addr, word in enumerate(words):
            byte_val = (word >> shift) & 0xFF
            f.write(f"\t{addr:04X} : {byte_val:02X};\n")
        f.write("END;\n")
    print(f"Wrote {path}  ({len(words)} entries, firmware={len([w for w in words if w])} non-zero words)")

print(f"\nDone. First instruction: 0x{words[0]:08X}")
print(f"Last non-zero at word {max((i for i,w in enumerate(words) if w), default=0)}")
